# Generated by Django 2.2.6 on 2019-10-25 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorado',
            fields=[
                ('usuario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Usuario')),
                ('semestre', models.SmallIntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno')], default=1)),
                ('carrera', models.CharField(choices=[('Ingenieria de Software', 'SOF'), ('Ingenieria en Computacion', 'INC'), ('Licenciatura en Informatica', 'INF'), ('Ingenieria en Telecomunicaciones y Redes', 'TEL'), ('Licenciatura en Administracion de las T.I.', 'ATI')], max_length=50)),
            ],
        ),
    ]
