# Generated by Django 2.2.6 on 2019-10-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutored', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorado',
            name='carrera',
            field=models.CharField(choices=[('Ingenieria de Software', 'SOF'), ('Ingenieria en Computacion', 'INC'), ('Licenciatura en Informatica', 'INF'), ('Ingenieria en Telecomunicaciones y Redes', 'TEL'), ('Licenciatura en Administracion de las T.I.', 'ATI')], default='Ingenieria de Software', max_length=50),
        ),
    ]
