# Generated by Django 2.2.6 on 2019-10-22 13:53

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.IntegerField(default=0)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=80)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_tutorado', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_profesor', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.users.models.get_upload_path_user_image)),
                ('descripcion', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
