# Generated by Django 2.2.6 on 2020-03-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_area', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especialidad', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=35)),
                ('lugar', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField(default='04:00:pm')),
                ('hora_final', models.TimeField(default='04:00:pm')),
                ('subarea_especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_area.SubAreasEspecialidad')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.Tutor')),
            ],
        ),
    ]
