# Generated by Django 2.2.6 on 2020-03-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorships', '0002_notificacionnuevohorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionnuevohorario',
            name='mensaje',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
