# Generated by Django 2.2.6 on 2020-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorships', '0003_notificacionnuevohorario_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotutoria',
            name='disponible',
            field=models.BooleanField(default=1),
        ),
    ]
