# Generated by Django 2.2.6 on 2020-05-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorships', '0004_horariotutoria_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotutoria',
            name='en_espera',
            field=models.BooleanField(default=0),
        ),
    ]
