# Generated by Django 2.2.6 on 2020-05-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tutorships', '0005_horariotutoria_en_espera'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAgendarTutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_tutorado', models.BooleanField(default=False)),
                ('estado', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_tutor', to='users.Usuario')),
                ('tutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_tutorado', to='users.Usuario')),
                ('tutoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoria', to='tutorships.HorarioTutoria')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificacionNuevoHorario',
        ),
    ]
