# Generated by Django 2.2.6 on 2020-05-19 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tutorships', '0006_auto_20200509_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=0)),
                ('motivo', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='notificacionagendartutoria',
            name='vistp_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(blank=True, max_length=60)),
                ('estado_tutoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_tutoria', to='tutorships.EstadoTutoria')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_tutoria', to='users.Usuario')),
                ('tutorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorado_tutoria', to='users.Usuario')),
                ('tutoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_tutoria', to='tutorships.HorarioTutoria')),
            ],
        ),
        migrations.CreateModel(
            name='TutoresTutorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores_tutorado_tutor', to='users.Usuario')),
                ('tutorado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutores_tutorado_tutorado', to='users.Usuario')),
            ],
        ),
    ]
